site_name: Tannhäuser Gate
site_url: http://chenleileicode.com
site_author: Chen Leilei
site_description: My Learning Notes

# Repository
repo_name: silverbulllet/my-mkdocs
repo_url: https://github.com/silverbulllet/my-mkdocs
edit_uri: ""

# Copyright
copyright: Copyright &copy; Chenleilei 2020 

# Configuration
theme:
  name: material
  custom_dir: src # overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: teal
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  # favicon: assets/favicon.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
# extra:

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Learning Notes:
    - learning notes/Javascript 设计模式.md
    - learning notes/Koa源码解析.md
    - learning notes/Typescript 学习笔记.md
    - learning notes/Webpack 5 探索.md
    - learning notes/作用域链与执行上线文.md
    - learning notes/原型链与继承.md
    - learning notes/手撸 Promise.md
    - learning notes/浏览器内核模块.md
    - learning notes/闭包.md
  - Serverless:
    - Concept: serverless/concept.md
    - Openfaas: serverless/openfaas.md
    - Knative: serverless/knative.md
    - 技术分享草稿: serverless/serverless-docs tmp notes.md 
  - Kubernetes:
    - Etcd: kubernetes/etcd deploy.md
    - kubeadm deployment: kubernetes/kubeadm-deployment.md
    - Calico: kubernetes/init-master-for-calico.sh.md
    - Kubernetes 插件: kubernetes/kube-addons.md
    - Kubernetes 证书: kubernetes/kube-certs.md
    - Istio: kubernetes/kube-istio.md
    - prometheus: kubernetes/kube-prometheus.md
    - storage: kubernetes/kube-storage.md
    - openfaas: kubernetes/kube-openfaas.md
    - openfaas-cloud: kubernetes/kube-openfaas-cloud.md
    - tekton: kubernetes/kube-tekton.md
    - knative: kubernetes/kube-knative.md
  - History:
    - history/Docker 学习笔记.md
    - history/Electron 学习笔记.md
    - history/JavaScript 之 Advanced Algorithms.md
    - history/JavaScript 之二叉树.md
    - history/JavaScript 之十大经典排序算法.md
    - history/JavaScript 之图和图类算法.md
    - history/JavaScript 事件模型.md
    - history/Javascript 之重复一个字符串n次.md
    - history/Javascript 学习之 Object.defineProperty().md
    - history/Javascript 学习之 this.md
    - history/Javascript 学习之深拷贝和浅拷贝.md
    - history/Javascript 能力测评经典题.md
    - history/Koa2+MongoDB 构建 Restful 后端.md
    - history/NodeJS 常用包及功能.md
    - history/PWA 之 Service Worker.md
    - history/Vuejs 学习笔记之基础篇（上）.md
    - history/Vuejs 学习笔记之基础篇（下）.md
    - history/Vuejs 学习笔记之状态管理 Vuex.md
    - history/Vuejs 学习笔记之过渡动画.md
    - history/Web实用工具收集.md
    - history/图解 HTTP 学习笔记.md
    - history/基于 CodeIgniter 的运维监控系统实现.md
    - history/基础知识杂记.md
  - About: about.md
